In [ ]:
## 00 PyTorch Fundamentals

In [ ]:
print("Hello I am now learning PyTorch!!!")

Hello I am now learning PyTorch!!!


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cpu


In [ ]:
## Introduction to Tensors

###creating tensors

###Scalar

scalar = torch.tensor(7)
scalar.ndim


0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,3,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 3, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR2 = torch.tensor([[[1,2,3],
                         [4,7,8],
                         [9,8,7],
                        [4,5,6],
                        [4,7,8],
                        [9,3,7]
                        ]])


In [ ]:
TENSOR2.ndim

3

In [ ]:
TENSOR2.shape

torch.Size([1, 6, 3])

In [ ]:
## Random tensors
## Why? Neural networks start with tensors full of random numbers then adjust those to get answer

random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.5305, 0.6594, 0.6019, 0.2583],
        [0.1995, 0.7171, 0.5589, 0.5186],
        [0.9302, 0.8535, 0.6983, 0.6673]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Similar to image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) ## height, width, color
random_image_size_tensor

tensor([[[0.0403, 0.4152, 0.8212],
         [0.4564, 0.7191, 0.3880],
         [0.7231, 0.1876, 0.9241],
         ...,
         [0.1971, 0.8767, 0.6519],
         [0.5124, 0.1411, 0.1498],
         [0.3282, 0.0187, 0.1172]],

        [[0.2096, 0.0803, 0.6284],
         [0.3797, 0.6537, 0.5861],
         [0.1574, 0.7552, 0.4615],
         ...,
         [0.4030, 0.1424, 0.5430],
         [0.3305, 0.8283, 0.3026],
         [0.4975, 0.9156, 0.7042]],

        [[0.1154, 0.1769, 0.1745],
         [0.7998, 0.5223, 0.9748],
         [0.0583, 0.9593, 0.7481],
         ...,
         [0.6412, 0.3497, 0.0830],
         [0.4909, 0.9714, 0.4976],
         [0.2174, 0.9576, 0.7302]],

        ...,

        [[0.8859, 0.2825, 0.3848],
         [0.6667, 0.8134, 0.1699],
         [0.4649, 0.3454, 0.3833],
         ...,
         [0.8602, 0.8854, 0.9063],
         [0.1318, 0.4517, 0.8272],
         [0.9381, 0.2700, 0.8940]],

        [[0.7450, 0.9532, 0.7750],
         [0.7598, 0.9522, 0.6352],
         [0.

In [ ]:
### Zeros & ones

# All zeros
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
### Creating a range of tensors and tensors-like

one_to_ten = torch.arange(start =1, end=1000, step=50)
one_to_ten

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [ ]:
# Creating tensors like

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
### Tensor Datatypes

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device="cpu",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device="cpu",
                               requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2742, 0.2701, 0.5929, 0.4189],
        [0.4590, 0.1532, 0.5302, 0.9306],
        [0.4441, 0.9323, 0.2356, 0.5324]])

In [ ]:
print(some_tensor)
print(f'Tensor Attributes')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')


tensor([[0.2742, 0.2701, 0.5929, 0.4189],
        [0.4590, 0.1532, 0.5302, 0.9306],
        [0.4441, 0.9323, 0.2356, 0.5324]])
Tensor Attributes
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
### Manipulating tensors

tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

# Multiplication element wise above

tensor([10, 20, 30])

In [ ]:
### Matrix Multiplication( dot product)

%%time
print(f'Matrix Multiplication {torch.matmul(tensor,tensor)}')


Matrix Multiplication 14
CPU times: user 369 µs, sys: 917 µs, total: 1.29 ms
Wall time: 18 ms


In [ ]:
##Shape errors

##

# 1. Inner dimension must match (@ is multiplication same a matmiul)
# (3,2) @ (3,2) won't work
# (2,3) @ (3,2) will work
# (3,2) @ (2,3) will work

# 2. Resulting Matrix has the shape of the outer dimension
torch.matmul(torch.rand(3,2), torch.rand(3,2))


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.9698, 0.7810],
        [0.8172, 0.8229]])

In [ ]:
#Shape for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm same a torch.matmul

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can transpose one of these tensor so they multiply


In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
## Finding min, max, sum

x = torch.arange(0,100,10)
x



tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
## converting to float as mean only take float or long

torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

In [ ]:

#Positional min, max


torch.argmin(x),x.argmin()

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
x[9]


tensor(90)

In [ ]:
## Reshaping, stacking, squeezing and unsqeezing

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
## Change the view

z = x.view(1,9)
z, z.shape



(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#chaning z changes x as z shares teh same memory as x

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
y = x_reshaped.view(1,9)
y,x_reshaped

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
# Stack tesnosr on top of each other

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Squeeze & unSqueeze

x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Permute rearranges dimensions ina specificed order

x_original = torch.rand(224,224,3) # example for image data
x_original

tensor([[[9.4034e-01, 3.8315e-01, 1.6971e-01],
         [9.0006e-01, 7.5132e-01, 2.0991e-01],
         [3.7138e-02, 2.8818e-01, 2.2607e-01],
         ...,
         [7.8167e-01, 6.9576e-01, 6.4135e-02],
         [1.6541e-01, 5.1280e-01, 7.7106e-02],
         [4.9569e-01, 7.7607e-01, 3.6448e-01]],

        [[8.2963e-01, 7.3917e-01, 6.9916e-01],
         [7.6810e-01, 8.0475e-01, 4.0153e-03],
         [5.2071e-01, 9.6398e-01, 4.4234e-01],
         ...,
         [9.3699e-01, 6.9222e-01, 5.4417e-01],
         [3.7824e-01, 2.8929e-01, 8.5989e-01],
         [4.5240e-01, 2.2035e-02, 1.9618e-01]],

        [[4.7719e-01, 5.7209e-01, 1.7856e-01],
         [5.6269e-01, 7.6328e-01, 7.0046e-01],
         [1.5528e-01, 9.0263e-01, 2.0783e-01],
         ...,
         [5.6838e-01, 4.8143e-01, 4.5212e-01],
         [8.5339e-01, 9.8634e-01, 8.2566e-01],
         [4.1872e-01, 1.1542e-01, 8.6333e-01]],

        ...,

        [[3.4128e-01, 2.7306e-01, 5.2216e-01],
         [2.4788e-02, 2.6847e-01, 1.0963e-01]

In [ ]:
x_permute = x_original.permute(2,0,1)

In [ ]:
x_permute.shape

torch.Size([3, 224, 224])

In [ ]:
x_permute

tensor([[[9.4034e-01, 9.0006e-01, 3.7138e-02,  ..., 7.8167e-01,
          1.6541e-01, 4.9569e-01],
         [8.2963e-01, 7.6810e-01, 5.2071e-01,  ..., 9.3699e-01,
          3.7824e-01, 4.5240e-01],
         [4.7719e-01, 5.6269e-01, 1.5528e-01,  ..., 5.6838e-01,
          8.5339e-01, 4.1872e-01],
         ...,
         [3.4128e-01, 2.4788e-02, 9.8330e-01,  ..., 9.0866e-01,
          2.8339e-01, 6.9850e-01],
         [3.6947e-01, 6.8578e-01, 6.8354e-01,  ..., 7.8608e-01,
          1.8534e-01, 9.1796e-01],
         [3.5508e-01, 2.7234e-01, 8.4274e-02,  ..., 8.7451e-01,
          7.9879e-01, 1.1181e-01]],

        [[3.8315e-01, 7.5132e-01, 2.8818e-01,  ..., 6.9576e-01,
          5.1280e-01, 7.7607e-01],
         [7.3917e-01, 8.0475e-01, 9.6398e-01,  ..., 6.9222e-01,
          2.8929e-01, 2.2035e-02],
         [5.7209e-01, 7.6328e-01, 9.0263e-01,  ..., 4.8143e-01,
          9.8634e-01, 1.1542e-01],
         ...,
         [2.7306e-01, 2.6847e-01, 1.3661e-01,  ..., 9.7012e-02,
          1.974

In [ ]:
# Indexing

x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

In [ ]:
# dim =1
x[0][0]

tensor([1, 2, 3])

In [ ]:
# most inner bracket, last dimension
x[0][0][0]

tensor(1)

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# index 9
x[0][2][2]

tensor(9)

In [ ]:
#NumPy

import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Reproducibility

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)



tensor([[0.9496, 0.0726, 0.3161, 0.9218],
        [0.8610, 0.7888, 0.1807, 0.2707],
        [0.3953, 0.7527, 0.5946, 0.5260]])
tensor([[0.2325, 0.5522, 0.6253, 0.7555],
        [0.9367, 0.8363, 0.7454, 0.6800],
        [0.2027, 0.5359, 0.7985, 0.5543]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Making this determintic
#works for only 1 block of code at a time

import torch

RANDOM_SEED = 44

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])
tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
# Acessing GPUs

#1

!nvidia-smi


Sun Mar  8 14:20:01 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   61C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
torch.cuda.is_available()

True

In [ ]:
#setup code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device

torch.cuda.device

In [ ]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [ ]:
## Putting tensors (and models) on GPU

tensor = torch.tensor([1,2,3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
## back to CPU; NumPy requires cpu

tensor_on_cpu = tensor_on_gpu.cpu().numpy()

In [ ]:
tensor_on_cpu

array([1, 2, 3])