In [1]:
## 00 PyTorch Fundamentals

In [2]:
print("Hello I am now learning PyTorch!!!")

Hello I am now learning PyTorch!!!


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [5]:
## Introduction to Tensors

###creating tensors

###Scalar

scalar = torch.tensor(7)
scalar.ndim


0

In [6]:
# get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,3,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 3, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR2 = torch.tensor([[[1,2,3],
                         [4,7,8],
                         [9,8,7],
                        [4,5,6],
                        [4,7,8],
                        [9,3,7]
                        ]])


In [19]:
TENSOR2.ndim

3

In [20]:
TENSOR2.shape

torch.Size([1, 6, 3])

In [21]:
## Random tensors
## Why? Neural networks start with tensors full of random numbers then adjust those to get answer

random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.3660, 0.5593, 0.7433, 0.0566],
        [0.4615, 0.3348, 0.0196, 0.1531],
        [0.6419, 0.0567, 0.1658, 0.6416]])

In [22]:
random_tensor.ndim

2

In [23]:
# Similar to image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) ## height, width, color
random_image_size_tensor

tensor([[[0.6074, 0.9898, 0.3075],
         [0.0341, 0.2058, 0.2435],
         [0.7681, 0.3702, 0.2433],
         ...,
         [0.7964, 0.2805, 0.2002],
         [0.9991, 0.7930, 0.4271],
         [0.5646, 0.7596, 0.5977]],

        [[0.0548, 0.8270, 0.1999],
         [0.7714, 0.1508, 0.3600],
         [0.3776, 0.4344, 0.7083],
         ...,
         [0.0249, 0.0729, 0.9325],
         [0.6617, 0.9470, 0.5031],
         [0.9430, 0.0955, 0.4398]],

        [[0.6583, 0.7826, 0.4877],
         [0.0023, 0.3633, 0.3042],
         [0.4210, 0.1419, 0.2840],
         ...,
         [0.5550, 0.0836, 0.5846],
         [0.2080, 0.7027, 0.1850],
         [0.4030, 0.0356, 0.1725]],

        ...,

        [[0.8453, 0.7129, 0.9575],
         [0.8270, 0.4915, 0.9333],
         [0.0202, 0.7287, 0.3812],
         ...,
         [0.2507, 0.7726, 0.2267],
         [0.4664, 0.3772, 0.2820],
         [0.4250, 0.2580, 0.0755]],

        [[0.1029, 0.0809, 0.2198],
         [0.8028, 0.6387, 0.1287],
         [0.

In [24]:
### Zeros & ones

# All zeros
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
### Creating a range of tensors and tensors-like

one_to_ten = torch.arange(start =1, end=1000, step=50)
one_to_ten

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [31]:
# Creating tensors like

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
### Tensor Datatypes

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device="cpu",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device="cpu",
                               requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [40]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [41]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [43]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3375, 0.8770, 0.6485, 0.6769],
        [0.1408, 0.2133, 0.0051, 0.4830],
        [0.9829, 0.9333, 0.0365, 0.0716]])

In [51]:
print(some_tensor)
print(f'Tensor Attributes')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')


tensor([[0.3375, 0.8770, 0.6485, 0.6769],
        [0.1408, 0.2133, 0.0051, 0.4830],
        [0.9829, 0.9333, 0.0365, 0.0716]])
Tensor Attributes
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [46]:
### Manipulating tensors

tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [47]:
tensor -10

tensor([-9, -8, -7])

In [48]:
torch.mul(tensor,10)

# Multiplication element wise above

tensor([10, 20, 30])

In [54]:
### Matrix Multiplication( dot product)

%%time
print(f'Matrix Multiplication {torch.matmul(tensor,tensor)}')


Matrix Multiplication 14
CPU times: user 461 µs, sys: 0 ns, total: 461 µs
Wall time: 337 µs
